### ISSUE TITLE
[BUG] - Bij het gebruik van de component in combinatie met lit-element, is het niet mogelijk om een dynamisch label en value te maken

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-rich-data-table#48]
**Omschrijf het probleem**
We willen de component in lit-element gebruiken met een dynamisch label ie: 
```
<vl-rich-data-field>
    <template slot="label">
        <span style="font-weight: normal">Project o.l.v.</span> <strong>manager</strong>
    </template>
    <template slot="content">
        <span>${item.name}</span> o.l.v. <strong>${item.manager.firstName} ${item.manager.lastName}</strong>
    </template>
</vl-rich-data-field>
```
maar de browser geeft een fout dat item niet defined is.
**Hoe te reproduceren**
Voorbeeld is te vinden in branch DSI2-768

**Gewenst gedrag**
Dat we dit wel zo kunnen doen in litelement

**Screenshots**
![image](https://user-images.githubusercontent.com/5698858/79437857-095ae400-7fd3-11ea-84b4-a34bfd90efd7.png)

**Omgeving (gelieve aan te vullen):**
 - Chrome
 - 80.0.3987.163
 - 1.0.0

**Extra info**
Workaround is ook in de branch te zien

**Comment by coemans** [comment]
@Pieter-Beckers kan jij dit bekijken? Ik heb nog doorgekregen dat er een workaround is. Ik vermoed, voor zo ver ik zicht heb op het probleem, dat dit ook de definitieve oplossing zal zijn.

```HTML
<vl-rich-data-table id="rich-data-table">
   <vl-rich-data-field>
     <template slot="label">
         ID
     </template>
     <template slot="content">
        ${'${item.id}'}
     </template>
   </vl-rich-data-field>
   <vl-rich-data-field>
     <template slot="label">
         LABEL
     </template>
     <template slot="content">
        ${'${item.label}'}
     </template>
   </vl-rich-data-field>
</vl-rich-data-table>
```

**Comment by pharacyde** [comment]
ik weet niet of het eenvoudig is, maar de template slots vervangen door een render functie zouden heel wat binding issues kunnen fixen. 

`
const idContentRenderer = (root, item) => ...;
`
root is hier waar de  render moet binden.
item is een van de items in de lijst die je rendert.

`<vl-rich-data-table id="rich-data-table">
   <vl-rich-data-field label="ID" contentRenderer="${idContentRenderer}" />
   ...
</vl-rich-data-table>
`
Ik weet anders niet hoe het verder moet met de workaround als we een select of een andere component die databinding nodig heeft, willen binden.

**Comment by SBylemans** [comment]
@Pieter-Beckers hoe staat het hiermee?

Loop nu tegen een probleem aan waarbij we een knop willen toevoegen als deel van de rich data field en een link die op het `item` staat. De code ziet er als volgt uit:

```
return html`
    <button is="vl-button" @click="${() => api.delete('item._links.verwijderLink.href')}">..</button>
`;
```

Waarbij die click event dus door litelement wordt afgehandeld en dus de `item._links.verwijderLink.href''` niet zal geresolved worden..

**Comment by Pieter-Beckers** [comment]
Met dat er een workaround was, was deze even opzij geschoven, maar ik pik deze zo snel mogelijk op!

**Comment by Pieter-Beckers** [comment]
> @Pieter-Beckers hoe staat het hiermee?
> 
> Loop nu tegen een probleem aan waarbij we een knop willen toevoegen als deel van de rich data field en een link die op het `item` staat. De code ziet er als volgt uit:
> 
> ```
> return html`
>     <button is="vl-button" @click="${() => api.delete('item._links.verwijderLink.href')}">..</button>
> `;
> ```
> 
> Waarbij die click event dus door litelement wordt afgehandeld en dus de `'item._links.verwijderLink.href'` niet zal geresolved worden..

Even bekeken, en niet direct iets proper gevonden. Probleem is dat de innerHTML van de template gekopieerd wordt en dus alles van custom lit element code niet mee wordt genomen. Mogelijke oplossing is om de listener er achteraf aan te hangen (bvb in `firstUpdated`), maar dan moet er wel in de shadow dom van de rich table gegaan worden om die button op te vragen:
```
this.component.shadowRoot.getElementById("button1").addEventListener('click', () => console.log('Clicked!'));
``` 
met template:
```
<template slot="label">
    <button id="button1" is="vl-button">Click me</button>
    ID
</template>
```
@coemans zie jij nog een andere workaround of oplossing?

**Comment by coemans** [comment]
@SBylemans en @pharacyde ik heb een voorstel uitgewerkt via de branch #lit-element-binding. Kunnen jullie eens kijken of deze branch de issues oplost? In de header is het complexer om custom bindings toe te laten, aangezien daar automatisch het sorteer element gerenderd moet worden. Ik verwacht niet meteen custom bindings in de header, dus lijkt me dat momenteel niet problematisch.

Hier alvast mijn lit-element voorbeeld ter illustratie:
```JavaScript
import { LitElement, html } from "https://unpkg.com/lit-element/lit-element.js?module"
import { render } from 'https://unpkg.com/lit-html@1.2.1/lit-html.js?module';

class VlRichDataTableLitTest extends LitElement {
    render() {
        return html`
            <vl-rich-data-table id="rich-data-table"
                data-vl-data='{"data": [{"id": 0, "name": "Project #1", "manager": {"firstName": "Pascal", "lastName": "Riquier"}, "medewerkers": [{"firstName": "Sander", "lastName": "Kleykens"}]}, 
                    {"id": 1, "name": "Project #2", "manager": {"firstName": "Tom", "lastName": "Coemans"}, "medewerkers": [{"firstName": "Guy", "lastName": "Wauters"}]}]}'>
                <vl-rich-data-field data-vl-label="ID" data-vl-selector="id"></vl-rich-data-field>
                <vl-rich-data-field data-vl-label="Naam" data-vl-selector="name"></vl-rich-data-field>
                <vl-rich-data-field data-vl-label="Naam manager" data-vl-selector="manager.lastName"></vl-rich-data-field>
                <vl-rich-data-field data-vl-label="Eerste medewerker" data-vl-selector="medewerkers.0.lastName"></vl-rich-data-field>
                <vl-rich-data-field .renderer="${this._renderer}">
                    <template slot="label">
                        <span style="font-weight: normal">Project o.l.v.</span> <strong>manager</strong>
                    </template>
                </vl-rich-data-field>
            </vl-rich-data-table>
        `;
    }

    _renderer(root, item) {
        render(html`
            <span @click="${() => console.log('value click')}">${item.name} o.l.v. <strong>${item.manager.firstName} ${item.manager.lastName}</strong></span>
        `, root);
    }
}

customElements.define("vl-rich-data-table-lit-test", VlRichDataTableLitTest);
```

**Comment by pharacyde** [comment]
ok bedankt, Sander zal het straks of vrijdag bekijken.

**Comment by SBylemans** [comment]
@coemans dit lijkt het probleem op te lossen. De gebruikte component moet nog juist op de methode gebind worden dus het render attribuut wordt: `.renderer="${this._renderer.bind(this)}"` om `this` in de methode te kunnen gebruiken.

**Comment by coemans** [comment]
> @coemans dit lijkt het probleem op te lossen. De gebruikte component moet nog juist op de methode gebind worden dus het render attribuut wordt: `.renderer="${this._renderer.bind(this)}"` om `this` in de methode te kunnen gebruiken.

@SBylemans inderdaad, mijn voorbeeld was maar ter informatie. Prima, dan werk ik dit zo snel als mogelijk verder af. Indien nodig, kunnen jullie natuurlijk al gebruik maken van deze branch.

**Comment by pharacyde** [comment]
@SBylemans @coemans 

`.renderer="${(root, item) => this._renderer(root, item)}"`

zou ook moeten werken, dan moet je de ES5 construct met bind(this) niet doen.
